# Generated by Django 3.2 on 2024-03-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldparameter',
            name='tab',
            field=models.IntegerField(default=0, verbose_name='Вкладка'),
        ),
        migrations.AlterField(
            model_name='fieldparameter',
            name='tag',
            field=models.SlugField(max_length=32, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='fieldparameter',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='record',
            name='dt',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='recorddata',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Занчение'),
        ),
        migrations.AlterField(
            model_name='template',
            name='tag',
            field=models.SlugField(max_length=16, unique=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Обязательно для заполнения'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='tab',
            field=models.IntegerField(default=0, verbose_name='Вкладка'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='tag',
            field=models.SlugField(max_length=32, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='type',
            field=models.CharField(choices=[('T', 'Text'), ('B', 'Bool'), ('E', 'E-mail'), ('U', 'URL'), ('C', 'Choices')], max_length=1, verbose_name='Тип поля'),
        ),
    ]
