# Generated by Django 3.2 on 2024-03-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_auto_20240306_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldparameter',
            options={'verbose_name': 'Поле формы', 'verbose_name_plural': 'Поля формы'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='recorddata',
            options={'verbose_name': 'Заполненная форма', 'verbose_name_plural': 'Заполненные формы'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Шаблон', 'verbose_name_plural': 'Шаблоны'},
        ),
        migrations.AlterModelOptions(
            name='templatefield',
            options={'verbose_name': 'Поле в шаблоне', 'verbose_name_plural': 'Поле в шаблоне'},
        ),
    ]
