# Generated by Django 3.2 on 2024-03-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_auto_20240306_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='type',
            field=models.CharField(choices=[('I', 'Integer'), ('T', 'Text'), ('B', 'Bool'), ('E', 'E-mail'), ('U', 'URL'), ('C', 'Choices')], max_length=1, verbose_name='Тип поля'),
        ),
    ]
