# Generated by Django 4.2.11 on 2024-03-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_alter_templatefield_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldparameter',
            name='tab',
            field=models.IntegerField(default=0, verbose_name='Очередность'),
        ),
        migrations.AlterField(
            model_name='recorddata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='onboarding.templatefield'),
        ),
        migrations.AlterField(
            model_name='recorddata',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='onboarding.record'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='tab',
            field=models.IntegerField(default=0, verbose_name='Очередность'),
        ),
    ]
